language: clojure
lein: lein2
sudo: true
services:
  - elasticsearch
env:
  - ES_CLUSTER_NAME=elasticsearch
before_install:
  - "ulimit -u 4096"
  - "sudo service elasticsearch status"
script: lein2 all test :ci
jdk:
  - openjdk7
  - oraclejdk8
